#Numpy


In [1]:
import numpy as np

In [2]:
ls=[1,2,3]
arr=np.array(ls)
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [5]:
arr.size

3

In [6]:
arr.shape

(3,)

In [15]:
np.array([1,2.5,3,0,5.6],dtype='int')


array([1, 2, 3, 0, 5])

In [19]:
new_arr=np.array([[7,25,33],
         [2,5,6],
         [1,0,9]])

In [20]:
new_arr.ndim

2

In [ ]:
np.array([[[[]]]]).ndim  #jitna square brackets utna dimension

4

In [22]:
np.array([[7,25,33],
         [2,5,6],
         [1,0,None]])

array([[7, 25, 33],
       [2, 5, 6],
       [1, 0, None]], dtype=object)

In [25]:
list(range(1,12))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [31]:
np.arange(1,10,4)

array([1, 5, 9])

In [28]:
np.arange(1.5,10.5,2)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [33]:
arr=np.array([[1,23,3],[2,5,6]])
arr

array([[ 1, 23,  3],
       [ 2,  5,  6]])

In [39]:
arr.reshape(3,2)

array([[ 1, 23],
       [ 3,  2],
       [ 5,  6]])

In [41]:
arr.flatten() #Make it 1D array

array([ 1, 23,  3,  2,  5,  6])

In [42]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [44]:
np.zeros((2,3)) #2 rows and 3 columns of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3,4))  #2 blocks, 3 rows and 4 columns of ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [46]:
np.full(10,5) #1D array of 10 elements with value 5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [47]:
np.full((2,3,4),7) #2 blocks, 3 rows and 4 columns of sevens

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [50]:
np.full([2,3],[9,6,7])

array([[9, 6, 7],
       [9, 6, 7]])

In [55]:
np.identity(4) #Identity matrix of size 4x4. Diagonal elements are 1 and rest are 0 
#we can also use np.eye(4) for the same purpose

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.random.randint(1,10,5) #Random integer between 1 and 10, 5 times

array([9, 7, 8, 8, 1], dtype=int32)

In [60]:
np.random.randint(200,3000,[3,4]) #2 rows and 3 columns of random numbers between 200 and 3000

array([[2604, 2833, 1076, 1541],
       [1989,  702, 1512, 2699],
       [2018,  853, 2089, 1464]], dtype=int32)

In [61]:
np.random.rand(2,3) #2 rows and 3 columns of random numbers between 0 and 1

array([[0.37004443, 0.14946417, 0.19076016],
       [0.4809626 , 0.15589511, 0.0133442 ]])

In [62]:
np.random.rand(1,10,5) #

array([[[0.08867492, 0.07931949, 0.97764426, 0.22270197, 0.21734911],
        [0.4598837 , 0.23041034, 0.69499734, 0.31059191, 0.53859157],
        [0.24122161, 0.87759712, 0.87851439, 0.55785872, 0.17769126],
        [0.06692912, 0.0303184 , 0.65260206, 0.03180038, 0.95667455],
        [0.55147769, 0.84996142, 0.25796302, 0.25174049, 0.19584125],
        [0.87501022, 0.75505622, 0.40336613, 0.36307925, 0.76748754],
        [0.43984804, 0.96937973, 0.04676321, 0.66344695, 0.62963134],
        [0.61079303, 0.08160232, 0.53650894, 0.16903952, 0.0501521 ],
        [0.98961512, 0.39140288, 0.00256831, 0.46521414, 0.72920472],
        [0.58945357, 0.34837316, 0.88992405, 0.69186354, 0.72748656]]])

In [ ]:
np.linspace(2,5,3) #show 3 value with equally distribution

array([2. , 3.5, 5. ])

In [64]:
arr=np.arange(1,11).reshape([2,5])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### copy and view 

In [68]:
new_arr_copy=arr.copy()
new_arr_copy

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [69]:
arr[0][0]=1000
arr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [70]:
new_arr_copy

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])